<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2017 Intenso (https://www.getintenso.com)
 * @license     http://getintenso.com/license
 */
?>
<?php $_product = $this->getProduct(); ?>
<a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->__('Product Detail') ?>" class="button secondary product-detail"><?php echo $this->__('Product Detail') ?></a>