<?php
/**
 * Intenso Premium Theme
 *
 * @category    Itactica
 * @package     Itactica_Intenso
 * @copyright   Copyright (c) 2014-2017 Intenso (https://www.getintenso.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php $themeHelper = Mage::helper('itactica_intenso'); ?>
<?php
$_menu = $this->getHtml('level-top');
$_linksArray = @unserialize(Mage::getStoreConfig('intenso/header/main_menu_links', Mage::app()->getStore()));
$_offcanvasLinksArray = @unserialize(Mage::getStoreConfig('intenso/header/mobile_offcanvas_links', Mage::app()->getStore()));
?>

<nav class="top-bar right-off-canvas-menu expanded main-nav <?php echo Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()); ?>" data-topbar>
    <ul class="title-area">
        <li class="name show-for-small-only">
            <?php echo $this->getChildHtml('offcanvasSearch') ?>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><?php echo $this->__('Menu'); ?></a></li>
    </ul>
    <section class="top-bar-section clearfix <?php echo Mage::getStoreConfig('intenso/header/main_menu_event', Mage::app()->getStore()); ?>">
        <!-- Right Nav Section -->
		<div class="top-bar-section-container">
			<ul class="right show-for-large-up">
					
				<li>
				<?php $catalogSearchHelper =  $this->helper('catalogsearch'); ?>
				<form method="get" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" id="search_mini_form">
					<div class="form-search">
						<div class="action">
							<button class="button" title="Search" type="submit"><span aria-hidden="true" class="icon-search"></span></button>
						</div>
						<?php echo $this->getChildHtml('topSearch') ?>
					</div>
				</form>				
				</li>			
			</ul>
			<!-- Left Nav Section -->
			<ul class="left">
				<?php if (Mage::getStoreConfig('intenso/header/show_home_link', Mage::app()->getStore()) ||
					Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?>
					<li class="last<?php if (Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?> show-for-small-only<?php endif; ?>">
						<a href="<?php echo $this->getUrl('') ?>"><span class="show-for-small-only icon-home"></span><?php echo $this->__('Home'); ?></a>
					</li>
				<?php endif; ?>
		  <?php if (Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?>
			<li class="level0 last has-dropdown hide-for-small-only vertical-menu-link mega-menu">
			  <a href="<?php echo $this->getUrl('') ?>">
				<span class="sup"><?php echo $this->__('Shop by'); ?></span>
				<span class="vmenu-title"><?php echo $this->__('Category'); ?></span>
			  </a>
			</li>
		  <?php endif; ?>
				<?php if (Mage::getStoreConfig('intenso/header/show_categories', Mage::app()->getStore())): ?>
					<li class="show-for-small-only group-title"><?php echo $this->__('Shop'); ?></li>
					<?php if ($_menu): ?>
						<?php echo $_menu ?>
					<?php endif ?>
				<?php endif ?>
				<?php if ($_linksArray): ?>
					<?php foreach ($_linksArray as $menuItem): ?>
						<li class="level0 hide-for-small-only custom-menu<?php if ($menuItem['classname']) echo ' '.$menuItem['classname']; ?><?php if ($menuItem['type']==1): ?> has-dropdown has-dropdown-for-large<?php elseif($menuItem['type']==2): ?> has-dropdown mega-menu has-dropdown-for-large<?php endif; ?>">
							<a href="<?php echo rtrim($this->getUrl($menuItem['url']), '/'); ?>" class="level0 has-children"><?php echo $menuItem['menu_item']; ?></a>
							<?php if ($menuItem['static_block'] && !$menuItem['type']==0): ?>
								<div class="dropdown custom-dropdown arrow-box">
									<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($menuItem['static_block'])->toHtml(); ?>
								</div>
							<?php endif; ?>
						</li>
					<?php endforeach; ?>
				<?php endif; ?>
				<li class="show-for-small-only group-title"><?php echo $this->__('Pages'); ?></li>
				<li class="show-for-small-only"><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $this->__('Cart'); ?></a></li>
				<li class="show-for-small-only"><a href="<?php echo $this->getUrl('customer/account'); ?>"><?php echo $this->__('Your Account'); ?></a></li>
				<?php if ($this->helper('wishlist')->isAllow()): ?>
					<li class="show-for-small-only"><a href="<?php echo $this->getUrl('wishlist'); ?>"><?php echo $this->__('Your Wish List'); ?></a></li>
				<?php endif; ?>
				<?php if ($_offcanvasLinksArray): ?>
					<?php foreach ($_offcanvasLinksArray as $menuItem): ?>
						<li class="show-for-small-only"><a href="<?php echo rtrim($this->getUrl($menuItem['url']), '/'); ?>"><?php echo $menuItem['menu_item']; ?></a></li>
					<?php endforeach; ?>
				<?php endif; ?>
			</ul>
		</div>
	</section>
</nav>

