<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2017 Intenso (https://www.getintenso.com)
 * @license     http://getintenso.com/license
 */
/**
 * @var $this Mage_ConfigurableSwatches_Block_Catalog_Product_List_Price
 */
?>
<script type="text/javascript">
    new ConfigurableSwatchPrices(<?php echo $this->getJsonConfig(); ?>);
</script>
