<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2017 Intenso (https://www.getintenso.com)
 * @license     http://getintenso.com/license
 */
/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */

?>

<?php
    $_cartQty = $this->helper('checkout/cart')->getSummaryCount();
    if(empty($_cartQty)) {
        $_cartQty = 0;
    }
    echo $_cartQty;
?>
